// <auto-generated />
using System;
using Back_Wiki;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Back_Wiki.Migrations
{
    [DbContext(typeof(DbInteractor))]
    partial class DbInteractorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Back_Wiki.Articles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("pageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("snippet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            pageId = 222,
                            snippet = "awdasdasdas",
                            timestamp = new DateTime(2020, 7, 16, 17, 31, 37, 577, DateTimeKind.Utc).AddTicks(7811),
                            title = "title"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
